"""Add description column to tasks

Revision ID: 2d0d89b5cd4c
Revises: ecdca53555f8
Create Date: 2024-11-24 23:04:20.045431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0d89b5cd4c'
down_revision: Union[str, None] = 'ecdca53555f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_tasks_slug', table_name='tasks')
    op.drop_index('ix_tasks_user_id', table_name='tasks')
    op.drop_column('tasks', 'slug')
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'content')
    op.drop_index('ix_users_slug', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_slug', 'users', ['slug'], unique=1)
    op.add_column('tasks', sa.Column('content', sa.VARCHAR(), nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.INTEGER(), nullable=True))
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    op.add_column('tasks', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_slug', 'tasks', ['slug'], unique=1)
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
