"""Add slug field to User model

Revision ID: 91ca65396b3e
Revises: 2d0d89b5cd4c
Create Date: 2024-11-24 23:40:05.925273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ca65396b3e'
down_revision: Union[str, None] = '2d0d89b5cd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
